language: cpp
os: linux
sudo: required
services: docker

branches:
  only:
  - master
  - devel
  # regex to match valid tag format or TravisCI won't trigger deploys when a new tag is pushed
  - /^v[0-9]+\.[0-9]+\.[0-9]+.*$/

script:
- make CONCURRENCY=4 package-debian-buster-dbuild
- make CONCURRENCY=4 package-debian-stretch-dbuild
- make CONCURRENCY=4 package-debian-jessie-dbuild
- make CONCURRENCY=4 package-fedora-22-dbuild

before_deploy: |
  # move packages to ARTIFACTS directory
  pushd packages
  mkdir ARTIFACTS
  ## rename debian packages to be distribution specific and move them to ARTIFACTS directory
  for DEBIAN_PKG in debian-*/libsuperiormysqlpp-dev_*.deb; do
    echo "*** DEBIAN_PKG = ${DEBIAN_PKG}"
    GITHUB_ARTIFACT_NAME=`echo ${DEBIAN_PKG} | sed --regexp-extended 's|debian-([^/]+)/libsuperiormysqlpp-dev_([^_]+)_amd64.deb|ARTIFACTS/libsuperiormysqlpp-dev_\2-\1_amd64.deb|'`
    echo "Renaming & moving package '${DEBIAN_PKG}' to '${GITHUB_ARTIFACT_NAME}'"
    mv ${DEBIAN_PKG} ${GITHUB_ARTIFACT_NAME}
  done
  ## move RPM packages to ARTIFACTS directory
  mv --target-directory=ARTIFACTS fedora-*/*.rpm
  popd
  # GitHub relaser script (https://github.com/lindell/github-release-cli)
  # used because standard github-release deploy module doesn't support specifying release message from ENV
  curl https://github.com/lindell/github-release-cli/releases/download/1.3.0/github-releaser-travis --fail --location --output github-releaser && chmod +x github-releaser \
    || (echo "Failed to download github-releaser script" && return 1)
  ## get changes from debian's changelog
  export BODY=`dpkg-parsechangelog --file packages/_debian-common/changelog --show-field Changes | grep --invert-match --extended-regexp '^$|^libsuperiormysqlpp |^  \[ '`
  export FILES=packages/ARTIFACTS/*

deploy:
  provider: script
  script: ./github-releaser -draft -verbose
  skip_cleanup: true
  on:
    tags: true
